export const FIGURES = [
  {
    name: "Man",
    domElement: "man",
    imagePath: "./img/man.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Business_man",
  },
  {
    name: "Woman",
    domElement: "woman",
    imagePath: "./img/woman.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Woman_03",
  },
  {
    name: "Table",
    domElement: "table",
    imagePath: "./img/table.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Furniture",
    type: "Table_01",
  },
  {
    name: "Bicycle",
    domElement: "bicycle",
    imagePath: "./img/bicycle.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Bike",
  },
  {
    name: "Factory",
    domElement: "factory",
    imagePath: "./img/factory.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "Factory",
  },
  {
    name: "Meeting Room",
    domElement: "meetingroom",
    imagePath: "./img/meeting_room.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Meeting_Room_01",
  },
  {
    name: "Coffee Corner",
    domElement: "coffeecorner",
    imagePath: "./img/coffee_corner.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Coffee_Corner_01",
  },
  {
    name: "Home",
    domElement: "homeButton",
    imagePath: "./img/home.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Home_01",
  },
  {
    name: "Kitchen",
    domElement: "kitchenButton",
    imagePath: "./img/kitchen.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Kitchen_01",
  },
  {
    name: "Office Room",
    domElement: "officeroom",
    imagePath: "./img/office_room.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Office_Room_01",
  },
];
