export const FIGURES = [
  {
    name: "Man",
    domElement: "man",
    imagePath: "./img/man.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Business_man",
  },
  {
    name: "Woman",
    domElement: "woman",
    imagePath: "./img/woman.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Woman_03",
  },
  {
    name: "Old Man",
    domElement: "oldman",
    imagePath: "./img/old_man.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Old_man",
  },
  {
    name: "Girl",
    domElement: "girl",
    imagePath: "./img/girl.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Girl",
  },
  {
    name: "Schoolboy",
    domElement: "schoolboy",
    imagePath: "./img/schoolboy.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Schoolboy",
  },
  {
    name: "Mechanic",
    domElement: "mechanic",
    imagePath: "./img/mechanic.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Character",
    type: "Mechanic",
  },
  {
    name: "Speech Bubble",
    domElement: "speechbubble",
    imagePath: "./img/speech_bubble.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Speech Bubble",
    type: "bubble",
  },
  {
    name: "Speech Bubble 2",
    domElement: "speechbubble2",
    imagePath: "./img/speech_bubble_2.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Speech Bubble",
    type: "bubble2",
  },
  {
    name: "Thought",
    domElement: "thought",
    imagePath: "./img/thought.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Speech Bubble",
    type: "thought",
  },
  {
    name: "Arrow Up",
    domElement: "arrow_up",
    imagePath: "./img/arrow_up.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Arrows",
    type: "arrow_up",
  },
  {
    name: "Arrow Down",
    domElement: "arrow_down",
    imagePath: "./img/arrow_down.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Arrows",
    type: "arrow_down",
  },
  {
    name: "Arrow Right",
    domElement: "arrow_right",
    imagePath: "./img/arrow_right.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Arrows",
    type: "arrow_right",
  },
  {
    name: "Arrow Left",
    domElement: "arrow_left",
    imagePath: "./img/arrow_left.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Arrows",
    type: "arrow_left",
  },
  {
    name: "Sign",
    domElement: "sign",
    imagePath: "./img/sign.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Signs",
    type: "sign",
  },
  {
    name: "Signs",
    domElement: "signs",
    imagePath: "./img/signs.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Signs",
    type: "signs",
  },
  {
    name: "Table",
    domElement: "table",
    imagePath: "./img/table.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Furniture",
    type: "Table_01",
  },
  {
    name: "Desk",
    domElement: "desk",
    imagePath: "./img/desk.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Furniture",
    type: "Desk",
  },
  {
    name: "Flipchart",
    domElement: "flipchart",
    imagePath: "./img/flipchart.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Furniture",
    type: "Flipchart",
  },
  {
    name: "Laptop",
    domElement: "laptop",
    imagePath: "./img/laptop.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Device",
    type: "Laptop",
  },
  {
    name: "Phone",
    domElement: "phone",
    imagePath: "./img/phone.glb",
    scale: {
      x: 1,
      y: 1,
      z: 1,
    },
    dropHeight: 0.5,
    positionLabel: 3,
    class: "Device",
    type: "Phone",
  },
  {
    name: "Bicycle",
    domElement: "bicycle",
    imagePath: "./img/bicycle.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Bike",
  },
  {
    name: "Car",
    domElement: "car",
    imagePath: "./img/car.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Car",
  },
  {
    name: "Bus",
    domElement: "bus",
    imagePath: "./img/bus.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Bus",
  },
  {
    name: "Train",
    domElement: "train",
    imagePath: "./img/train.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Train",
  },
  {
    name: "Truck",
    domElement: "truck",
    imagePath: "./img/truck.glb",
    scale: {
      x: 2,
      y: 2,
      z: 2,
    },
    dropHeight: 1,
    positionLabel: 3,
    class: "Transportation_Element",
    type: "Truck",
  },
  {
    name: "House",
    domElement: "house",
    imagePath: "./img/house.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "House",
  },
  {
    name: "Building",
    domElement: "building",
    imagePath: "./img/building.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "Building",
  },
  {
    name: "Office",
    domElement: "office",
    imagePath: "./img/office.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "Office",
  },
  {
    name: "Factory",
    domElement: "factory",
    imagePath: "./img/factory.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "Factory",
  },
  {
    name: "Station",
    domElement: "station",
    imagePath: "./img/station.glb",
    scale: {
      x: 5,
      y: 5,
      z: 5,
    },
    dropHeight: 2.5,
    positionLabel: 6.5,
    class: "Building",
    type: "Station",
  },
  {
    name: "Meeting Room",
    domElement: "meetingroom",
    imagePath: "./img/meeting_room.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Meeting_Room_01",
  },
  {
    name: "Coffee Corner",
    domElement: "coffeecorner",
    imagePath: "./img/coffee_corner.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Coffee_Corner_01",
  },
  {
    name: "Home",
    domElement: "homeButton",
    imagePath: "./img/home.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Home_01",
  },
  {
    name: "Kitchen",
    domElement: "kitchenButton",
    imagePath: "./img/kitchen.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Kitchen_01",
  },
  {
    name: "Office Room",
    domElement: "officeroom",
    imagePath: "./img/office_room.glb",
    scale: {
      x: 6,
      y: 6,
      z: 6,
    },
    dropHeight: 3,
    positionLabel: 7,
    class: "Background",
    type: "Office_Room_01",
  },
];
